name: docker-image
on: [push]
jobs:
  createImg:
    runs-on: ubuntu-latest
    steps:
      #check the repo
      - uses: actions/checkout@v2
      #build the docker image
      - run: docker build -t hello-alpine ../..
      #Github Container registry Login
      - run: login --username khiba-k --password ${{secrets.CR_PAT }} ghcr.io
      #Push image to registry
      - run: docker push ghcr.io/${{ github.repository }}/my-image:latest
