name: docker-image
on: [push]
jobs:
  createImg:
    runs-on: ubuntu-latest
    steps:
      #check the repo
      - uses: actions/checkout@v4
      #build the docker image
      - run: docker build -t hello-alpine .
      #Github Container registry Login
      - run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      #Push image to registry
      - run: docker push ghcr.io/${{ github.repository }}/my-image:latest
